name: Cargo build Cache
description: Cargo build Cache
inputs:
  rustc-commit-hash:
    description: Commit hash of the rustc version
    required: true
  profile:
    description: Cargo profile used
    required: true
runs:
  using: composite
  steps:
    - name: Cargo build Cache
      uses: actions/cache@v2
      with:
        # https://doc.rust-lang.org/cargo/guide/build-cache.html
        path: |
          target/
        key: cargo-build-${{ runner.os }}-${{ runner.arch }}-${{ inputs.rustc-commit-hash }}-${{ inputs.profile }}-${{ hashFiles('**/Cargo.toml') }}-${{ github.sha }}
        restore-keys: |
          cargo-build-${{ runner.os }}-${{ runner.arch }}-${{ inputs.rustc-commit-hash }}-${{ inputs.profile }}-${{ hashFiles('**/Cargo.toml') }}-
          cargo-build-${{ runner.os }}-${{ runner.arch }}-${{ inputs.rustc-commit-hash }}-${{ inputs.profile }}-
          cargo-build-${{ runner.os }}-${{ runner.arch }}-${{ inputs.rustc-commit-hash }}-
